Take any checkerbaord: even on our laptop screen should be ok, i used my own laptop ( do check with scale the size of squares and update in 6th cell accordingly)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Run this if you have video as input for calibration
import cv2
import os
import matplotlib.pyplot as plt

video_path = "/content/drive/My Drive/calibration_images/24_checkerboard.mp4"
output_path = "/content/drive/My Drive/calibration_images/good_frames"
os.makedirs(output_path, exist_ok=True)

cap = cv2.VideoCapture(video_path)
frame_count = 0
saved_count = 0
#use this to divide fps to avoid similar images
fps_divider = 1
fps = cap.get(cv2.CAP_PROP_FPS)

#or manually set step as suited
step = max(int(fps/fps_divider), 1)
print(fps,step)

In [ ]:
#Run this if you have video as input for calibration
import cv2
import os
import matplotlib.pyplot as plt

video_path = "/content/drive/My Drive/calibration_images/24_checkerboard.mp4"
output_path = "/content/drive/My Drive/calibration_images/good_frames"
os.makedirs(output_path, exist_ok=True)

cap = cv2.VideoCapture(video_path)
frame_count = 0
saved_count = 0
#use this to divide fps to avoid similar images
fps_divider = 1
fps = cap.get(cv2.CAP_PROP_FPS)

#or manually set step as suited
step = max(int(fps/fps_divider), 1)
print(fps,step)

In [ ]:
#to delete ALL frames form folder
folder_path = "/content/drive/My Drive/calibration_images/good_frames"

for filename in os.listdir(folder_path):
    file_path = os.path.join(folder_path, filename)
    print(file_path)
    if os.path.isfile(file_path):
        os.remove(file_path)

print("All files removed")

start from here with frames else use above module for good (checkerboard corners detectable) frame extraction from video

In [2]:
#Else start from here if you have frames
# MOST IMPORTANT STEP IS TO SET square_size in code cell below this cell
#also set the path here
import os
path = "/content/drive/My Drive/calibration_images/good_frames"
files = os.listdir(path)
print(files)

['frame_0.jpg', 'frame_1.jpg', 'frame_2.jpg', 'frame_3.jpg', 'frame_4.jpg', 'frame_6.jpg', 'frame_7.jpg', 'frame_9.jpg', 'frame_10.jpg', 'frame_14.jpg', 'frame_15.jpg', 'frame_16.jpg', 'frame_22.jpg', 'frame_23.jpg', 'frame_24.jpg', 'frame_27.jpg', 'frame_28.jpg', 'frame_29.jpg', 'frame_32.jpg', 'frame_35.jpg']


In [ ]:
square_size = 26  # in millimeters( the size of square, please measure with scale if necessary this needs to be accurate)
CHECKERBOARD = (8,6)  # 8 inner row corner, 6 inner coloumn corner(count inner corners only and set it to here, not outer total corners)

In [ ]:
import cv2
import numpy as np
import glob
import matplotlib.pyplot as plt




#termination criteria for corner refinement: subpixel accuracy for better localization of the exact corner
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

#prepare 3D object points
objp = np.zeros((CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
objp *= square_size  # scale to real-world units

objpoints = []  #3D points
imgpoints = []  #2D points

# image_paths = glob.glob(path + "/*.jpg")
# path = "/content/drive/My Drive/calibration_images/new"
for path_ in files:
    img_path = os.path.join(path, path_)

    img = cv2.imread(img_path)
    print("boya")
    print(path_)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, None)

    if ret:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)


        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
        plt.figure(figsize=(8,6))
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        plt.title(os.path.basename(path))
        plt.axis('off')
        plt.show()


Output hidden; open in https://colab.research.google.com to view.

In [4]:
print("Number of valid images with detected corners:", len(objpoints))

print("Shape of last gray image:", gray.shape[::-1])
ret, K, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

print("Calibration successful")
print("\nCamera Matrix (K):\n", K)
print("\nDistortion Coefficients:\n", dist.ravel())
print("rvec: ", rvecs)
# HERER LIES CAMERA Intrisics:

Number of valid images with detected corners: 20
Shape of last gray image: (3840, 1644)
Calibration successful

Camera Matrix (K):
 [[1.94141391e+03 0.00000000e+00 1.88812703e+03]
 [0.00000000e+00 1.94472299e+03 8.23596947e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Distortion Coefficients:
 [ 0.01991167 -0.15226447 -0.00020439  0.0014133   0.19155372]
rvec:  (array([[ 0.05685221],
       [-0.00755844],
       [-0.00469818]]), array([[ 0.05919267],
       [-0.02732309],
       [-0.01205198]]), array([[ 0.07070636],
       [-0.17624672],
       [-0.05813428]]), array([[ 0.10075998],
       [-0.26647793],
       [-0.06139666]]), array([[ 0.10710496],
       [-0.27782067],
       [-0.06793851]]), array([[ 0.30603719],
       [-0.10446924],
       [-0.01822469]]), array([[ 0.27553359],
       [-0.02811512],
       [-0.00219841]]), array([[0.0409392 ],
       [0.23261701],
       [0.11324934]]), array([[0.03463014],
       [0.20119424],
       [0.13386838]]), array([[-0.11950296]